### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by fabricionaweb** [zeit/micro-list#11]
It would be interesting if it had support gzip compression `-z, --gzip`
I consider useful for purposes of comparison with the size in production

**Comment by joakimbeng** [comment]
I needed this for another Micro microservice as well so I made [`micro-compress`](https://github.com/joakimbeng/micro-compress) which should be easy to integrate into this module...

**Comment by leo** [comment]
@joakimbeng Perfect! Also looks like a great addition to [this list](https://github.com/leo/awesome-zeit).

**Comment by slorber** [comment]
@leo @joakimbeng as far as I understand responses are compressed live.

This works but is not performant for static assets, because a frequently accessed asset would likely get recompressed everytime while it would probably be more efficient to memoize that compression per file.
