### ISSUE TITLE
Doesn't work with directories named with spaces

### ISSUE THREAD

**Issue by djalmaaraujo** [zeit/micro-list#5]
http://localhost:4444/ALL/EXT%20DOCUMENTS

Dir name: "EXT DOCUMENTS"

Results on "not found"

Steps to reproduce:

1 - Create a directory called "my custom folder"
2 - run list --port 4444 ~/path/to/parent/dir/of/my custom folder
3 - go to http://localhost:4444/
4 - Click on "my custom folder"
BOOM!

**Comment by rauchg** [comment]
@djalmaaraujo PRs welcome! Thanks for the report

**Comment by leo** [comment]
Should be fixed in 14ab2c6c4a0944af497524e253bf355cdc3da18a. Please confirm! A quick note though: It looks like the path on step 2 is wrong (the spaces should be escaped like shown below).

```
~/path/to/parent/dir/of/my\ custom\ folder/
```

**Comment by djalmaaraujo** [comment]
@leo Looks fixed. yay!

**Comment by djalmaaraujo** [comment]
@leo I don't know if it's related, but when go to the 3rd level, things get crazy. i am investigating the code, but for example, when I am on:

```/ALL/BGP%20DOCUMENTS/```

And try to open

```/ALL/BGP%20DOCUMENTS/DESIGN```

The url goes like this:

```/ALL/ALL/BGP%20DOCUMENTS/DESIGN``` (it is duplicating the ALL)

**Comment by djalmaaraujo** [comment]
@leo  fixed on #6

**Comment by leo** [comment]
@djalmaaraujo Everything is fixed now, correct?

**Comment by djalmaaraujo** [comment]
@leo yup.

One thing is missing that I couldn't find a good solution.. directories with "accents". For example: "Presentación". Maybe you can figure out later.

**Comment by rauchg** [comment]
We should be fine with `encodeURIComponent` ?

![image](https://cloud.githubusercontent.com/assets/13041/16179906/54a64aa0-3629-11e6-92e5-a94569818ead.png)

**Comment by djalmaaraujo** [comment]
@rauchg I tried and it doesn't work. Should we move to another issue? This one looks fixed. I will open one more.

**Comment by djalmaaraujo** [comment]
https://github.com/zeit/micro-list/issues/7
